# Generated by Django 3.1.3 on 2021-04-20 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, verbose_name='Название предмета')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, verbose_name='Имя пользователя')),
                ('Surname', models.CharField(max_length=30, verbose_name='Фамилия пользователя')),
                ('Groum', models.IntegerField(verbose_name='Группа')),
                ('Login', models.CharField(max_length=30, verbose_name='Логин пользователя')),
                ('Password', models.CharField(max_length=30, verbose_name='Пароль пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='Practices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(upload_to='', verbose_name='Практики')),
                ('Name', models.CharField(max_length=30, verbose_name='Имя практики')),
                ('Items_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_sait.items', verbose_name='Код предмета')),
            ],
        ),
        migrations.CreateModel(
            name='Lectures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(upload_to='', verbose_name='Лекции')),
                ('Name', models.CharField(max_length=30, verbose_name='Имя лекции')),
                ('Items_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_sait.items', verbose_name='Код предмета')),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('mark', models.IntegerField(verbose_name='Оценка')),
                ('Items_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_sait.items', verbose_name='Код предмета')),
                ('Users_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_sait.users', verbose_name='Код пользователя')),
            ],
        ),
    ]
