# Generated by Django 3.2 on 2021-04-23 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=None, verbose_name='Код группы')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название предмета')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=30, verbose_name='Имя пользователя')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия пользователя')),
                ('login', models.CharField(max_length=30, verbose_name='Логин пользователя')),
                ('password', models.CharField(max_length=30, verbose_name='Пароль пользователя')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_sait.groups', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Practices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='practices', verbose_name='Файл')),
                ('name', models.CharField(max_length=100, verbose_name='Имя практики')),
                ('date', models.DateField(verbose_name='Дата')),
                ('items_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_sait.items', verbose_name='Код предмета')),
            ],
            options={
                'verbose_name': 'Практика',
                'verbose_name_plural': 'Практики',
            },
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('mark', models.IntegerField(verbose_name='Оценка')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_sait.groups', verbose_name='Группа')),
                ('items_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_sait.items', verbose_name='Предмет')),
                ('users_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_sait.users', verbose_name='Код пользователя')),
            ],
            options={
                'verbose_name': 'Календарь',
                'verbose_name_plural': 'Календарь',
            },
        ),
        migrations.CreateModel(
            name='Lectures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lectures', verbose_name='Файл')),
                ('name', models.CharField(max_length=100, verbose_name='Имя лекции')),
                ('date', models.DateField(verbose_name='Дата')),
                ('items_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_sait.items', verbose_name='Код предмета')),
            ],
            options={
                'verbose_name': 'Лекция',
                'verbose_name_plural': 'Лекции',
            },
        ),
    ]
