# Generated by Django 3.2 on 2021-04-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_sait', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectures',
            name='file',
            field=models.FileField(blank=True, upload_to='lectures', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='practices',
            name='file',
            field=models.FileField(blank=True, upload_to='practices', verbose_name='Файл'),
        ),
    ]
