# Generated by Django 3.1.3 on 2021-04-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_sait', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar',
            options={'verbose_name': 'Календарь', 'verbose_name_plural': 'Календарь'},
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterModelOptions(
            name='lectures',
            options={'verbose_name': 'Лекция', 'verbose_name_plural': 'Лекции'},
        ),
        migrations.AlterModelOptions(
            name='practices',
            options={'verbose_name': 'Практика', 'verbose_name_plural': 'Практики'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RenameField(
            model_name='calendar',
            old_name='Items_code',
            new_name='items_code',
        ),
        migrations.RenameField(
            model_name='calendar',
            old_name='Users_code',
            new_name='users_code',
        ),
        migrations.RenameField(
            model_name='lectures',
            old_name='File',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='lectures',
            old_name='Items_code',
            new_name='items_code',
        ),
        migrations.RenameField(
            model_name='practices',
            old_name='File',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='practices',
            old_name='Items_code',
            new_name='items_code',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Groum',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Login',
            new_name='login',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Surname',
            new_name='surname',
        ),
        migrations.RemoveField(
            model_name='items',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='lectures',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='practices',
            name='Name',
        ),
        migrations.AddField(
            model_name='items',
            name='name',
            field=models.CharField(default='', max_length=150, verbose_name='Название предмета'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lectures',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Имя лекции'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practices',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Имя практики'),
            preserve_default=False,
        ),
    ]
