# Generated by Django 3.1.3 on 2021-04-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_sait', '0002_auto_20210420_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(default=None, max_length=30, verbose_name='Имя пользователя'),
        ),
    ]
