# Generated by Django 3.1.3 on 2021-04-21 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_sait', '0003_auto_20210420_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=None, verbose_name='Код группы')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.AlterField(
            model_name='lectures',
            name='file',
            field=models.FileField(upload_to='lectures', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='practices',
            name='file',
            field=models.FileField(upload_to='practices', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='my_sait.groups', verbose_name='Группа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_sait.groups', verbose_name='Группа'),
        ),
    ]
